export const ALL_COURSE_REQUEST = "ALL_COURSE_REQUEST";
export const ALL_COURSE_SUCCESS = "ALL_COURSE_SUCCESS";
export const ALL_COURSE_FAIL = "ALL_COURSE_FAIL";

export const ADMIN_COURSE_REQUEST = "ADMIN_COURSE_REQUEST";
export const ADMIN_COURSE_SUCCESS = "ADMIN_COURSE_SUCCESS";
export const ADMIN_COURSE_FAIL = "ADMIN_COURSE_FAIL";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

export const DELETE_LECTURE_REQUEST = "DELETE_LECTURE_REQUEST";
export const DELETE_LECTURE_SUCCESS = "DELETE_LECTURE_SUCCESS";
export const DELETE_LECTURE_FAIL = "DELETE_LECTURE_FAIL";

export const ADD_LECTURE_REQUEST = "ADD_LECTURE_REQUEST";
export const ADD_LECTURE_SUCCESS = "ADD_LECTURE_SUCCESS";
export const ADD_LECTURE_FAIL = "ADD_LECTURE_FAIL";

export const GET_COURSE_LECTURE_REQUEST = "GET_COURSE_LECTURE_REQUEST";
export const GET_COURSE_LECTURE_SUCCESS = "GET_COURSE_LECTURE_SUCCESS";
export const GET_COURSE_LECTURE_FAIL = "GET_COURSE_LECTURE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
