export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const KHALTI_PAYMENT_REQUEST = "KHALTI_PAYMENT_REQUEST";
export const KHALTI_PAYMENT_SUCCESS = "KHALTI_PAYMENT_SUCCESS";
export const KHALTI_PAYMENT_FAIL = "KHALTI_PAYMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
