name: Render Deployment

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: np03cs4m210054248/roboastroed

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: np03cs4m210054248/roboastroed:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Deploy to Render
      #   uses: roboastroed/render-deploy-action@v1
      #   with:
      #     service-id: ${{ secrets.SERVICE_ID }}
      #     api-key: ${{ secrets.RENDER_SECRET_KEY }}
      #     docker-image: np03cs4m210054248/roboastroed:${{ github.sha }}

