name: Render Deployment

on:
  push:
    branches:
      - backend

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Pull Docker Image
        run: docker pull yourusername/backend:latest

      - name: Tag Docker Image
        run: docker tag np03cs4m210054248/roboastroed:latest docker.io/np03cs4m210054248/roboastroed:v4

      - name: Push Docker Image
        run: docker push docker.io/np03cs4m210054248/roboastroed:v4

      - name: Deploy to Render
        uses: roboastroed/render-deploy-action@v1
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_SECRET_KEY }}
          docker-image: docker.io/np03cs4m210054248/roboastroed:v4
